<?xml version="1.0"?>
<!-- import xacro reffering here https://gbiggs.github.io/rosjp_urdf_tutorial_text/manipulator_urdf.html -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="left_arm" params="base_name *origin">
    <!-- Active joint 1 -->
    <joint name="active_joint_la" type="revolute">
      <parent link="${base_name}"/>
      <child link="link_1"/>
      <xacro:insert_block name="origin"/>
      <axis xyz="0 0 1"/>
      <limit lower="${ACTIVE_JOINT_LA_LOWER}" upper="${ACTIVE_JOINT_LA_UPPER}"
        effort="${ACTIVE_JOINT_LA_EFFORT}" velocity="${ACTIVE_JOINT_LA_VELOCITY}"/>
    </joint>

    <!-- Link 1 -->
    <link name="link_1">
      <visual>
        <origin xyz="0 0 ${LINK_1_Z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_1_X} ${LINK_1_Y} ${LINK_1_Z}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${LINK_1_Z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_1_X} ${LINK_1_Y} ${LINK_1_Z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="${LINK_1_MASS}" x="${LINK_1_X/2}" y="${LINK_1_Y/2}" z="${LINK_1_Z/2}">
        <origin xyz="0 0 ${LINK_1_Z/2}" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link>

    <!-- Joint 2 -->
    <joint name="active_joint_lb" type="revolute">
      <parent link="link_1"/>
      <child link="link_2"/>
      <origin xyz="0 0 ${LINK_1_Z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${ACTIVE_JOINT_LB_LOWER}" upper="${ACTIVE_JOINT_LB_UPPER}"
        effort="${ACTIVE_JOINT_LB_EFFORT}" velocity="${ACTIVE_JOINT_LB_VELOCITY}"/>
    </joint>

    <!-- Link 2 -->
    <link name="link_2">
      <visual>
        <origin xyz="${LINK_2_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_2_X} ${LINK_2_Y} ${LINK_2_Z}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="${LINK_2_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_2_X} ${LINK_2_Y} ${LINK_2_Z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="${LINK_2_MASS}" x="${LINK_2_X/2}" y="${LINK_2_Y/2}" z="${LINK_2_Z/2}">
        <origin xyz="${LINK_2_X/2} 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link>

    <!-- Joint 3 -->
    <joint name="active_joint_lc" type="revolute">
      <parent link="link_2"/>
      <child link="link_3"/>
      <origin xyz="${LINK_2_X} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${ACTIVE_JOINT_LC_LOWER}" upper="${ACTIVE_JOINT_LC_UPPER}"
        effort="${ACTIVE_JOINT_LC_EFFORT}" velocity="${ACTIVE_JOINT_LC_VELOCITY}"/>
    </joint>

    <!-- Link 3 -->
    <link name="link_3">
      <visual>
        <origin xyz="${LINK_3_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_3_X} ${LINK_3_Y} ${LINK_3_Z}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="${LINK_3_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_3_X} ${LINK_3_Y} ${LINK_3_Z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="${LINK_3_MASS}" x="${LINK_3_X/2}" y="${LINK_3_Y/2}" z="${LINK_3_Z/2}">
        <origin xyz="${LINK_3_X/2} 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link>
  </xacro:macro>

</robot>