<?xml version="1.0"?>
<!-- import xacro reffering here https://gbiggs.github.io/rosjp_urdf_tutorial_text/manipulator_urdf.html -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find spacediver_ros2_control)/description/urdf/macros/inertial_macros.xacro"/>
  <xacro:include filename="$(find spacediver_ros2_control)/description/urdf/macros/properties.xacro"/>

  <xacro:macro name="right_arm" params="base_name *origin">
    <!-- Joint 4 -->
    <joint name="joint_d" type="revolute">
      <parent link="right_arm"/>
      <child link="link_4"/>
      <origin xyz="${LINK_3_X} 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${ACTIVE_JOINT_RA_LOWER}" upper="${ACTIVE_JOINT_RA_UPPER}"
        effort="${ACTIVE_JOINT_RA_EFFORT}" velocity="${ACTIVE_JOINT_RA_VELOCITY}"/>
    </joint>

    <!-- Link 4 -->
    <link name="link_4">
      <visual>
        <origin xyz="${LINK_4_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_4_X} ${LINK_4_Y} ${LINK_4_Z}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="${LINK_4_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_4_X} ${LINK_4_Y} ${LINK_4_Z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="${LINK_4_MASS}" x="${LINK_4_X/2}" y="${LINK_4_Y/2}" z="${LINK_4_Z/2}">
        <origin xyz="${LINK_4_X/2} 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link>

    <!-- Joint 5 -->
    <joint name="joint_e" type="revolute">
      <parent link="link_4"/>
      <child link="link_5"/>
      <origin xyz="${LINK_4_X} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${ACTIVE_JOINT_RB_LOWER}" upper="${ACTIVE_JOINT_RB_UPPER}"
        effort="${ACTIVE_JOINT_RB_EFFORT}" velocity="${ACTIVE_JOINT_RB_VELOCITY}"/>
    </joint>

    <!-- Link 5 -->
    <link name="link_5">
      <visual>
        <origin xyz="${LINK_5_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_5_X} ${LINK_5_Y} ${LINK_5_Z}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="${LINK_5_X/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LINK_5_X} ${LINK_5_Y} ${LINK_5_Z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="${LINK_5_MASS}" x="${LINK_5_X/2}" y="${LINK_5_Y/2}" z="${LINK_5_Z/2}">
        <origin xyz="${LINK_5_X/2} 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link>

    <!-- Joint 6 -->
    <joint name="joint_f" type="revolute">
      <parent link="link_5"/>
      <child link="link_6"/>
      <origin xyz="${LINK_5_X} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${ACTIVE_JOINT_RC_LOWER}" upper="${ACTIVE_JOINT_RC_UPPER}"
        effort="${ACTIVE_JOINT_RC_EFFORT}" velocity="${ACTIVE_JOINT_RC_VELOCITY}"/>
    </joint>

    <link name="link_6">
    <visual>
      <origin xyz="${LINK_6_X/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${LINK_6_X} ${LINK_6_Y} ${LINK_6_Z}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="${LINK_6_X/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${LINK_6_X} ${LINK_6_Y} ${LINK_6_Z}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${LINK_6_MASS}" x="${LINK_6_X/2}" y="${LINK_6_Y/2}" z="${LINK_6_Z/2}">
      <origin xyz="${LINK_6_X/2} 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>
  </xacro:macro>

</robot>