<?xml version="1.0"?>
<!-- import xacro reffering here
https://gbiggs.github.io/rosjp_urdf_tutorial_text/manipulator_urdf.html -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="right_arm" params="base_name *origin">

    <!-- BASE TO SHOULDER -->
    <joint name="${BASE_TO_RIGHTSHOULDER_JOINT_NAME}" type="revolute">
      <parent link="${BASE_LINK_NAME}" />
      <child link="${R_SHOULDER_LINK_NAME}" />
      <origin
        xyz="${SHOULDER_POS_X} ${SHOULDER_JOINTA_X-SHOULDER_Y/2} 0"
        rpy="0 ${PI/2} 0" />
      <axis xyz="0 0 1" />
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1" />
    </joint>

    <!-- SHOULDER -->
    <link name="${R_SHOULDER_LINK_NAME}">
      <visual>
        <origin
          xyz="${-SHOULDER_Z/2} ${-SHOULDER_JOINTA_X} 0"
          rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <mesh
            filename="package://spacediver_ros2_control/description/gazebo/models/meshes/shoulder_plate.STL" />
        </geometry>
      </visual>
      <inertial>
        <origin xyz="0 0 0.25" rpy="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
    </link>


    <!-- Joint 2 -->
    <joint name="${RIGHT_DYNAMIXELBOT_TO_RIGHTMISUMILN_JOINT_NAME}" type="revolute">
      <parent link="${R_SHOULDER_LINK_NAME}" />
      <child link="${R_MISUMILN_LINK_NAME}" />
      <origin
        xyz="${SHOULDER_Z/2 - DYNAMIXEL_Z - 0.0145} 0 ${SHOULDER_X + DYNAMIXEL_X/2}"
        rpy="${-PI/2} ${-ROT} ${PI/2}" />
      <axis xyz="0 0 1" />
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1" />
    </joint>

    <!-- FIRST LINK -->
    <link name="${R_MISUMILN_LINK_NAME}">
      <visual>
        <origin
          xyz="${-MISUMILN_JOINTA_Y} ${-MISUMILN_JOINTA_X} 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://spacediver_ros2_control/description/gazebo/models/meshes/Link_MISUMI_LNMS16-10-200.STL" />
        </geometry>
        <material name="green">
          <color rgba="0 1 0 1" />
        </material>
      </visual>
      <inertial>
        <origin xyz="0 0 0.1" rpy="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
    </link>

    <!-- Joint 3 -->
    <joint name="${RIGHTDYNAMIXELTOP_TO_RIGHTDRIVING_JOINT_NAME}" type="revolute">
      <parent link="${R_MISUMILN_LINK_NAME}" />
      <child link="${R_DRIVING_LINK_NAME}" />
      <origin
        xyz="${MISUMILN_JOINTB_Y} 0 ${MISUMILN_Z}"
        rpy="0 0 ${PI/2 + ROT}" />
      <axis xyz="0 0 1" />
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1" />
      <mimic joint="${LEFT_DYNAMIXELBOT_TO_LEFTMISUMILN_JOINT_NAME}" multiplier="1" offset="0" />
    </joint>

    <!-- SECOND LINK -->
    <link name="${R_DRIVING_LINK_NAME}">
      <visual>
        <origin
          xyz="${-MISUMIFT_JOINTB_X} ${-MISUMIFT_JOINTB_Y} 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://spacediver_ros2_control/description/gazebo/models/meshes/Misumi_LNFTS10-P10-V10-L200-S50-W18-T9.STL" />
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1" />
        </material>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
    </link>


  </xacro:macro>

</robot>