---
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # List of controllers to start
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


### Controllers setup
# Full body controllers
joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_to_leftshoulder_joint
      - leftdynamixeltop_to_leftdriving_joint
      - leftdynamixelbottom_to_leftmisumiln_joint
    interface_name:
      - position
      - velocity
      - effort


position_trajectory_controller:
  ros__parameters:
    joints:
      - base_to_leftshoulder_joint
      - leftdynamixeltop_to_leftdriving_joint
      - leftdynamixelbottom_to_leftmisumiln_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gain:
      base_to_leftshoulder_joint:
        p: 100.0
        i: 10.0
        d: 3600.0

      leftdynamixeltop_to_leftdriving_joint:
        p: 100.0
        i: 10.0
        d: 3600.0
      
      leftdynamixelbottom_to_leftmisumiln_joint:
        p: 100.0
        i: 10.0
        d: 3600.0
