<?xml version="1.0" ?>
<sdf version="1.5" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find spacediver_ros2_control)/description/urdf/macros/properties.xacro"/>
  <model name="my1stmodel">
    <!-- ros_control plugin -->
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find spacediver_ros2_control)/bringup/config/spacediver_controllers.yaml</parameters>
    </plugin>

    <!-- Model -->
    <!-- parallel link is defined here but not in urdf -->
    <!-- active joints hsould have the same name as those in urdf -->
    <static>false</static>
    <link name="base_link">
      <!-- <pose>0 0 0 0 0 0</pose> -->
      <collision name="collision">
        <geometry>
          <box>
            <size>${BASE_X} ${BASE_Y} ${BASE_Z}</size>
          </box>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>100</mu>
              <mu2>50</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <visual name="visual">
        <geometry>
          <box>
            <size>${BASE_X} ${BASE_Y} ${BASE_Z}</size>
          </box>
        </geometry>
        <material>
          <script>
            <uri>file://media/materials/scripts/gazebo.material</uri>
            <name>Gazebo/Grey</name>
          </script>
        </material>
      </visual>
    </link>
    
    <link name="link_1">
      <pose>0 0 ${BASE_Z/2*}</pose>
      <collision name="collision">
        <geometry>
          <box>
            <size>${LINK_1_X} ${LINK_1_Y} ${LINK_1_Z}</size>
          </box>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>100</mu>
              <mu2>50</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <visual name="visual">
        <geometry>
          <box>
            <size>${LINK_1_X} ${LINK_1_Y} ${LINK_1_Z}</size>
          </box>
        </geometry>
        <material>
          <script>
            <uri>file://media/materials/scripts/gazebo.material</uri>
            <name>Gazebo/Red</name>
          </script>
        </material>
      </visual>
    </link>

    <joint name="active_joint_la" type="revolute">
      <parent>base_link</parent>
      <child>link_1</child>
      <axis>
        <xyz>0 1 0</xyz>
      </axis>
      <limit>
        <lower>${ACTIVE_JOINT_LA_LOWER}</lower>
        <upper>${ACTIVE_JOINT_LA_UPPER}</upper>
        <effort>${ACTIVE_JOINT_LA_EFFORT}</effort>
        <velocity>${ACTIVE_JOINT_LA_VELOCITY}</velocity>
      </limit>
    </joint>
  </model>
</sdf>